# Generated by Django 4.2.16 on 2024-11-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del taller')),
                ('descripcion', models.TextField(help_text='Una breve descripción del taller', verbose_name='Descripción breve')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección física')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo de contacto')),
                ('horario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario de atención')),
                ('enlace_facebook', models.URLField(blank=True, null=True, verbose_name='Enlace a Facebook')),
                ('enlace_instagram', models.URLField(blank=True, null=True, verbose_name='Enlace a Instagram')),
                ('enlace_whatsapp', models.URLField(blank=True, null=True, verbose_name='Enlace a WhatsApp')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo del taller')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_edicion', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
